development:
  app_name: Moneota
  ses_access_key_id: Secret
  ses_secret_access_key: SuperSecret
  mailer_address: mailer@email.com
  db_username: Matt
  db_password: password

test:
  app_name: Moneota
  ses_access_key_id: Secret
  ses_secret_access_key: SuperSecret
  mailer_address: mailer@email.com
  db_username: Matt
  db_password: password

production:
  app_name: Moneota
  ses_access_key_id: Secret
  ses_secret_access_key: SuperSecret
  mailer_address: mailer@email.com
  db_username: Matt
  db_password: password
